// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RL.Data;

#nullable disable

namespace RL.Data.Migrations
{
    [DbContext(typeof(RLContext))]
    [Migration("20260307094419_PlanProcedureUsers")]
    partial class PlanProcedureUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("RL.Data.DataModels.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedure", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("PlanProcedures");
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedureUser", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId", "ProcedureId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlanProcedureUsers");
                });

            modelBuilder.Entity("RL.Data.DataModels.Procedure", b =>
                {
                    b.Property<int>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedureTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProcedureId");

                    b.ToTable("Procedures");

                    b.HasData(
                        new
                        {
                            ProcedureId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Front Seat Control Switch - Removal and Installation - Front Seats",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Level Sender - Removal and Installation - Fuel Tank and Lines - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Specifications - Specifications - Suspension System - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Complete Panel Replacement/Partial Replacement - Description and Operation - Body Repairs - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Turbocharger LH - Removal and Installation - Fuel Charging and Controls - Turbocharger - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Front Center Seat Backrest Latch - Removal and Installation - Front Seats",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 7,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Electronic Engine Controls - Component Location - Description and Operation - Electronic Engine Controls - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 8,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Rocker Panel Inner Reinforcement - Regular Cab - Removal and Installation - Side Panel Sheet Metal Repairs",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel System - Overview - Description and Operation - Fuel System - General Information - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 10,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Rear Shock Absorber - Removal and Installation - Rear Suspension",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Charging and Controls - System Operation and Component Description - Description and Operation - Fuel Charging and Controls - 5.0L 32V Ti-VCT",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Specifications - Specifications - Parking Aid - Vehicles With: Rear Parking Aid",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 13,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "\"Noise, Vibration and Harshness (NVH) - Description and Operation - Noise, Vibration and Harshness\"",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 14,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Engine - Body On - Installation - Engine - 5.0L 32V Ti-VCT",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Accessory Drive - Component Location - Description and Operation - Accessory Drive - 3.3L Duratec-V6",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 16,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Charging and Controls - Component Location - Description and Operation - Fuel Charging and Controls - 3.3L Duratec-V6",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 17,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Front Seats - Diagnosis and Testing - Front Seats",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 18,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Autolamps - Diagnosis and Testing - Exterior Lighting",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 19,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Speaker Audio Test - General Procedures - Information and Entertainment System - General Information - Vehicles With: SYNC",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Brake Caliper - Removal and Installation - Rear Disc Brake",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 21,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Charging System - 2.7L EcoBoost (238kW/324PS)/3.5L EcoBoost (272kW/370PS) - Diagnosis and Testing - Charging System - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 22,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "\"Hood Latch Release Handle - Removal and Installation - Handles, Locks, Latches and Entry Systems\"",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 23,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Information and Entertainment System - Diagnosis and Testing - Information and Entertainment System - General Information - Vehicles Without: SYNC",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 24,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Rear Seats - Overview - Description and Operation - Rear Seats",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 25,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Tire Pressure Monitoring System (TPMS) - Overview - Description and Operation - Tire Pressure Monitoring System (TPMS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 26,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Charge Air Cooler (CAC) Outlet Pipe - Removal and Installation - Intake Air Distribution and Filtering - 2.7L EcoBoost (238kW/324PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 27,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Coolant Pump - Removal and Installation - Engine Cooling - 3.3L Duratec-V6",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 28,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Module Controlled Functions - System Operation and Component Description - Description and Operation - Multifunction Electronic Modules",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 29,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Specifications - Specifications - Engine Ignition - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 30,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Exhaust Manifold LH - Removal and Installation - Engine - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 31,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Passive Anti-Theft System (PATS) - Overview - Description and Operation - Passive Anti-Theft System (PATS) - Vehicles With: Keyless Vehicle System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 32,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Wastegate Control Valve Solenoid - Removal and Installation - Fuel Charging and Controls - Turbocharger - 2.7L EcoBoost (238kW/324PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 33,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Side Curtain Airbag - Regular Cab - Removal and Installation - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 34,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Valve Cover RH - Raptor - Removal and Installation - Engine - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 35,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Rear Suspension - Diagnosis and Testing - Rear Suspension",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 36,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Diesel Particulate Filter (DPF) Differential Pressure Sensor - Removal and Installation - Electronic Engine Controls - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 37,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Crankshaft Position (CKP) Sensor - Removal and Installation - Electronic Engine Controls - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 38,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "\"Thermostatic Expansion Valve - 3.5L EcoBoost (272kW/370PS), Raptor - Removal and Installation - Climate Control System - General Information\"",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 39,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Road Testing Vehicle - Diagnosis and Testing - Automatic Transmission - 6-Speed Automatic Transmission – 6R80",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 40,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Engine - Body On - Removal - Engine - 2.7L EcoBoost (238kW/324PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 41,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Restraints Control Module (RCM) - Removal and Installation - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 42,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Specifications - Specifications - Generator and Regulator",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 43,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Engine - Body Off - Removal - Engine - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 44,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Transfer Case - Diagnosis and Testing - Transfer Case",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 45,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Camshaft LH - Removal and Installation - Engine - 5.0L 32V Ti-VCT",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 46,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Low One-Way Clutch Assembly - Diagnosis and Testing - Automatic Transmission - 10-Speed Automatic Transmission – 10R80",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 47,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Pinpoint Test - DTC: M - Diagnosis and Testing - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 48,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Bodyside Moulding - Removal and Installation - Exterior Trim and Ornamentation",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 49,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Body Mount Fastener - General Procedures - Full Frame and Body Mounting",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 50,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Pinpoint Test - DTC: AP - Diagnosis and Testing - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 51,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Front Seat Cushion Blower Motor - Removal and Installation - Front Seats",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 52,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Alternating Current (AC) Power Outlet Socket - Removal and Installation - Voltage Converter/Inverter",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 53,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Downshift Paddle Switch - Removal and Installation - Automatic Transmission External Controls",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 54,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Pinpoint Test - DTC: H - Diagnosis and Testing - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 55,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Engine Oil Draining and Filling - General Procedures - Engine - 2.7L EcoBoost (238kW/324PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 56,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Transmission - Installation - Automatic Transmission - 6-Speed Automatic Transmission – 6R80",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 57,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Interior Rear View Mirror - Removal and Installation - Rear View Mirrors",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 58,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Camshaft RH - Removal and Installation - Engine - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 59,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Specifications - Specifications - Engine Ignition - 3.3L Duratec-V6",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 60,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Specifications - Specifications - Engine - 2.7L EcoBoost (238kW/324PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 61,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Rear Door Alignment - SuperCab - General Procedures - Body Closures",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 62,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "High-Pressure Fuel Pump - Removal and Installation - Fuel Charging and Controls - 3.3L Duratec-V6",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 63,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Roof Opening Panel Motor - Removal and Installation - Roof Opening Panel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 64,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Engine Ignition - Component Location - Description and Operation - Engine Ignition - 3.3L Duratec-V6",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 65,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Inspection and Repair after a Supplemental Restraint System (SRS) Deployment - General Procedures - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 66,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Transmission Fluid Cooler - 3.0L Power Stroke Diesel - Removal and Installation - Transmission Cooling",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 67,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Tank and Lines - Diagnosis and Testing - Fuel Tank and Lines - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 68,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Tank and Lines - Overview - Description and Operation - Fuel Tank and Lines - 5.0L 32V Ti-VCT",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 69,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Intake Air Distribution and Filtering - Overview - Description and Operation - Intake Air Distribution and Filtering - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 70,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Charge Air Cooler (CAC) Cleaning - Raptor - General Procedures - Intake Air Distribution and Filtering - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 71,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Cylinder Head - Disassembly and Assembly of Subassemblies - Engine - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 72,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Corrosion Prevention - General Procedures - Body Repairs - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 73,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Front Parking Aid Camera - Removal and Installation - Parking Aid - Vehicles With: Parking Aid Camera",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 74,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "\"Front Door Window Regulator and Motor - Vehicles With: Front Power Windows - Removal and Installation - Glass, Frames and Mechanisms\"",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 75,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Cylinder Head - Body On - LH - Raptor - Removal - Engine - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 76,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Tank - Vehicles With: Police Pack - Removal and Installation - Fuel Tank and Lines - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 77,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Starter Motor - Removal and Installation - Starting System - 2.7L EcoBoost (238kW/324PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 78,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Engine Emission Control - Diagnosis and Testing - Engine Emission Control - 3.3L Duratec-V6",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 79,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Specifications - Specifications - Starting System - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 80,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Pinpoint Test - DTC: D - Diagnosis and Testing - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 81,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "A Clutch - Diagnosis and Testing - Automatic Transmission - 10-Speed Automatic Transmission – 10R80",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 82,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Pinpoint Test - DTC: K - Diagnosis and Testing - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 83,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Blower Motor Control Module - Removal and Installation - Climate Control System - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 84,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Exhaust System - Diagnosis and Testing - Exhaust System - 2.7L EcoBoost (238kW/324PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 85,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Valve Cover RH - Removal and Installation - Engine - 5.0L 32V Ti-VCT",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 86,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Selector Lever Cable - Raptor - Removal and Installation - Automatic Transmission External Controls",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 87,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Turbocharger Oil Supply Tube RH - Raptor - Removal and Installation - Fuel Charging and Controls - Turbocharger - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 88,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Climate Control System - Vehicles With: Electronic Manual Temperature Control (EMTC) - Component Location - Description and Operation - Climate Control System - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 89,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Pinpoint Test - DTC: AN - Diagnosis and Testing - Supplemental Restraint System",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 90,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Accessory Drive - Component Location - Description and Operation - Accessory Drive - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 91,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "\"Rear Door Glass Run and Bracket - SuperCrew - Removal and Installation - Glass, Frames and Mechanisms\"",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 92,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "About this Manual - Description and Operation - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 93,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Engine Ignition - Diagnosis and Testing - Engine Ignition - 5.0L 32V Ti-VCT",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 94,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Injection Pump - Removal and Installation - Fuel Charging and Controls - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 95,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Glove Compartment - Removal and Installation - Instrument Panel and Console",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 96,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Tank and Lines - Diagnosis and Testing - Fuel Tank and Lines - 3.0L Power Stroke Diesel",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 97,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Fuel Rail Pressure and Temperature Sensor - Removal and Installation - Electronic Engine Controls - 3.5L EcoBoost (272kW/370PS)",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 98,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Wheel and Tire Health and Safety Precautions - Description and Operation - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 99,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Variable Camshaft Timing (VCT) Unit - Removal and Installation - Engine - 3.3L Duratec-V6",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 100,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Piston Selection - General Procedures - Engine System - General Information",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RL.Data.DataModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreateDate = new DateTime(1999, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nick Morrison",
                            UpdateDate = new DateTime(1999, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            CreateDate = new DateTime(1999, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Scott Cassidy",
                            UpdateDate = new DateTime(1999, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            CreateDate = new DateTime(1999, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tony Bidner",
                            UpdateDate = new DateTime(1999, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 4,
                            CreateDate = new DateTime(1999, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Patryk Skwarko",
                            UpdateDate = new DateTime(1999, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedure", b =>
                {
                    b.HasOne("RL.Data.DataModels.Plan", "Plan")
                        .WithMany("PlanProcedures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RL.Data.DataModels.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedureUser", b =>
                {
                    b.HasOne("RL.Data.DataModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RL.Data.DataModels.PlanProcedure", "PlanProcedure")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("PlanId", "ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanProcedure");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RL.Data.DataModels.Plan", b =>
                {
                    b.Navigation("PlanProcedures");
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedure", b =>
                {
                    b.Navigation("AssignedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
